teste = {
	{1, 2, 3},
	{4, 5, 6}
}

testeb = {
	pocca = 10
}

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		local pos = vmath.vector3(action.x, action.y, 0)
		local carrot_id = factory.create("/go#ball", pos)
		print(testeb["pocca"])
	end
end
