components {
  id: "block_base"
  component: "/main/scripts/block_base.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"block_blue\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/atlases/world.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"world\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 8.0\n"
  "      y: -8.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"collider\"\n"
  "  }\n"
  "  data: 8.0\n"
  "  data: 8.0\n"
  "  data: 8.0\n"
  "}\n"
  ""
}
